### ISSUE TITLE
chore: change to https link

### ISSUE THREAD

**Issue by alexanderblv** [matter-labs/foundry-zksync#363]
https://github.com/matter-labs/foundry-zksync/blob/eda90786d0a293dc63af5b8f27e3eae3c5e7196c/README.md?plain=1#L71

For public access, it is better to use an HTTPS link, as indicated in the official documentation
https://docs.zksync.io/build/
https://github.com/matter-labs/zksync-web-era-docs

**Comment by Karrq** [comment]
Actually, as per the [official](https://docs.zksync.io/build/tooling/foundry/getting-started.html#installation-guide) documentation instructs, an ssh link is more than fine

**Comment by alexanderblv** [comment]
> Actually, as per the [official](https://docs.zksync.io/build/tooling/foundry/getting-started.html#installation-guide) documentation instructs, an ssh link is more than fine

We are talking about public access. In this case, the HTTPS link looks preferable

**Comment by nbaztec** [comment]
HTTPS versus SSH remote link is entirely a subjective preference, and the linked documentation doesn't prefer any way as well. The repository's documentation in point contextually assumes the user is operating within the terminal, since they need to build the source and execute script immediately afterwards, where `git clone` is the preferred choice. 

Moreover, the repository contains references to git submodules that are cloned recursively when using `git clone`.
