### ISSUE TITLE
Error installing foundry-zksync 

### ISSUE THREAD

**Issue by Victoryeddy** [matter-labs/foundry-zksync#498]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

git clone git@github.com:matter-labs/foundry-zksync.git

### Operating System

macOS (Intel)

### Describe the bug

When i try to install foundry-zksync by following the 1st instruction ``` git clone git@github.com:matter-labs/foundry-zksync.git ```
i get an error 
```bash Cloning into 'foundry-zksync'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 
```

**Comment by elfedy** [comment]
@Victoryeddy  the error is due to github rejecting your ssh connection. The docs assume you have git and github set up correctly and that you can clone repos. Please see: https://docs.github.com/en/authentication/connecting-to-github-with-ssh.  Alternatively you can download the repo as a zip, and carry on with the instructions from there.
