### ISSUE TITLE
Cannot deploy a contract using a paymaster

### ISSUE THREAD

**Issue by lutr0** [matter-labs/foundry-zksync#724]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (d053ecd 2024-11-11T00:25:54.225428781Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Trying to deploy the counter contract using a paymaster
`source .env && forge script ./script/Counter.s.sol --rpc-url https://rpc.testnet.sophon.xyz/ --private-key $PRIVATE_KEY --zksync --broadcast`
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {Counter} from "../src/Counter.sol";

contract CounterScript is Script {
    Counter public counter;

    function setUp() public {}

    function run() public {
        vm.startBroadcast();
        bytes memory paymaster_encoded_input = abi.encodeWithSelector(
            bytes4(keccak256("general(bytes)")),
            bytes("0x")
        );
        vm.zkUsePaymaster(
            address(0x98546B226dbbA8230cf620635a1e4ab01F6A99B2),
            paymaster_encoded_input
        );
        // address(vm).call(
        //     abi.encodeWithSignature(
        //         "zkUsePaymaster(address,bytes)",
        //         address(0x98546B226dbbA8230cf620635a1e4ab01F6A99B2),
        //         paymaster_encoded_input
        //     )
        // );

        counter = new Counter();

        vm.stopBroadcast();
    }
}
```

1. Using vm.zkUsePaymaster:
```
[⠊] Compiling...
[⠑] Compiling 1 files with Solc 0.8.27
[⠘] Solc 0.8.27 finished in 588.57ms
Error: Compiler run failed:
Error (9582): Member "zkUsePaymaster" not found or not visible after argument-dependent lookup in contract Vm.
  --> script/Counter.s.sol:18:9:
   |
18 |         vm.zkUsePaymaster(
   |         ^^^^^^^^^^^^^^^^^
   ```

Doing `forge install Moonsong-Labs/forge-zksync-std` before gives no different output

2. address(vm).call

```
source .env && forge script ./script/Counter.s.sol --rpc-url $RPC_URL --private-key $PRIVATE_KEY --zksync --broadcast
[⠊] Compiling...
No files changed, compilation skipped
[⠃] Using zksolc-1.5.4
[⠊] Compiling (zksync)
No files changed, compilation skipped
The application panicked (crashed).
Message:  failed to find zksolc artifact with hash "01000019d25bde8a10855af114c524bcff837ba788f857e811eb7df0b0ca2fdf"
Location: crates/zksync/compiler/src/zksolc/mod.rs:175

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 7 frames hidden ⋮                               
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hc7471e4b6e7951f8
      at <unknown source file>:<unknown line>
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h8c486ad7f8519660
      at <unknown source file>:<unknown line>
  10: foundry_zksync_compiler::zksolc::DualCompiledContracts::new::h85ed00bca4451018
      at <unknown source file>:<unknown line>
  11: forge_script::build::PreprocessedState::compile::h9ac963fddcd34f3b
      at <unknown source file>:<unknown line>
  12: forge_script::ScriptArgs::run_script::{{closure}}::h8e4ce3b9c4016b64
      at <unknown source file>:<unknown line>
  13: tokio::runtime::park::CachedParkThread::block_on::he05a96c7bbdac95b
      at <unknown source file>:<unknown line>
  14: tokio::runtime::context::runtime::enter_runtime::h0baaf6400ee0b7c9
      at <unknown source file>:<unknown line>
  15: tokio::runtime::runtime::Runtime::block_on::hc45a0d891c20202a
      at <unknown source file>:<unknown line>
  16: forge::main::h20df304092543ce4
      at <unknown source file>:<unknown line>
  17: std::sys::backtrace::__rust_begin_short_backtrace::h5b755891f77bf632
      at <unknown source file>:<unknown line>
  18: std::rt::lang_start::{{closure}}::hdfa632be978c0979
      at <unknown source file>:<unknown line>
  19: std::rt::lang_start_internal::hfaad9e988507cb85
      at <unknown source file>:<unknown line>
  20: main<unknown>
      at <unknown source file>:<unknown line>
  21: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
  22: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:360
  23: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)
```

**Comment by Jrigada** [comment]
Hey @lutr0! Thanks for reporting this issue.

To address your first point, to use the high-level call with cheatcodes directly, you’ll need to install the `Moonsong-Labs/forge-zksync-std` package. You can do so by running:

```bash
forge install Moonsong-Labs/forge-zksync-std --no-commit
```

Once installed, you can access the zkSync-specific cheat codes by importing `TestExt` in your contract, like so:

```solidity
import {TestExt} from "forge-zksync-std/TestExt.sol";

contract YourContract is TestExt {
    vmExt.zkUsePaymaster(…)
}
```

This allows you to use the zksync specific cheatcodes directly, similar to executing the low-level call you mentioned in point 2. More info regarding vmExt can be found [here](https://foundry-book.zksync.io/zksync-specifics/forge-zksync-std)

Regarding the error, it appears to be related to cached compiled outputs. Cleaning the `zkout` directory (or the equivalent if you’ve remapped it) should resolve this, allowing your script to execute properly. I replicated your setup with `CounterScript` on the Sophon testnet, and you can view the successful transaction here:  
[Transaction on Sophon Explorer](https://explorer.testnet.sophon.xyz/tx/0x853b73261cb1051b828f5e863c843d2297c9d7c9326681a30f47af387143d59b)

At the end of the execution I did from my end, there’s an error message related to parsing the transaction receipt, but this doesn’t indicate a transaction failure, as shown in the link above. This issue was raised recently in [this discussion](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/766#discussioncomment-11215020) and should be resolved by updating the RPC node accordingly.
![image](https://github.com/user-attachments/assets/996a6789-d3ed-4304-a64a-82cac6e99030)


Let me know if this helps resolve the issue.

**Comment by Jrigada** [comment]
Hello @lutr0! We merged today the fix for the out of gas issue when using paymaster in simulation. Can you confirm from your end that it works? 
I tried this with a fresh new account without balance
https://explorer.testnet.sophon.xyz/tx/0xc81f9dcfe2b726a06ca5b84110dc51240e17b126da713cf05db50b829d8c7191

**Comment by lutr0** [comment]
Confirmed the fix as well https://explorer.testnet.sophon.xyz/address/0x44Cdb1e839A2c0D1E0d4f491a8CB14599D253281
Thanks for the support!
