### ISSUE TITLE
failed to get 'zk_evm'

### ISSUE THREAD

**Issue by kylinkang002** [matter-labs/foundry-zksync#98]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

Linux

### Describe the bug

 Updating crates.io index
    Updating git repository `https://github.com/mm-zk/ethers-rs`
    Updating git repository `https://github.com/matter-labs/zksync-era.git`
    Updating git submodule `https://github.com/matter-labs/era-contracts.git`
    Updating git submodule `https://github.com/matter-labs/era-openzeppelin.git`
    Updating git submodule `https://github.com/a16z/erc4626-tests.git`
    Updating git submodule `https://github.com/foundry-rs/forge-std`
    Updating git submodule `https://github.com/dapphub/ds-test`
    Updating git submodule `https://github.com/matter-labs/era-system-contracts.git`
    Updating git repository `https://github.com/matter-labs/solidity_plonk_verifier.git`
    Updating git repository `https://github.com/matter-labs/era-zk_evm.git`
error: failed to get `zk_evm` as a dependency of package `zksync_types v1.0.0 (https://github.com/matter-labs/zksync-era.git#44b265bd)`
    ... which satisfies git dependency `zksync_types` (locked to 1.0.0) of package `foundry-cli v0.2.0 (/home/k/work/era/fzksync/foundry-zksync/cli)`

Caused by:
  failed to load source for dependency `zk_evm`

Caused by:
  Unable to update https://github.com/matter-labs/era-zk_evm.git?branch=main#ca203a25

Caused by:
  object not found - no match for id (ca203a25cbff50ad623630e393dd041aca58038d); class=Odb (9); code=NotFound (-3)

**Comment by KittyFu307** [comment]
I also have this questions: 
Any update for the team?
error: failed to get `zk_evm` as a dependency of package `zksync_types v1.0.0 (https://github.com/matter-labs/zksync-era.git#44b265bd)`
    ... which satisfies git dependency `zksync_types` (locked to 1.0.0) of package `foundry-cli v0.2.0
Caused by:
  failed to load source for dependency `zk_evm`

Caused by:
  Unable to update https://github.com/matter-labs/era-zk_evm.git?branch=main#ca203a25

Caused by:
  object not found - no match for id (ca203a25cbff50ad623630e393dd041aca58038d); class=Odb (9); code=NotFound (-3)

**Comment by mm-zk** [comment]
Thanks for the report. #101 should fix it.
